// pSEO combination data for generating travel agent pages
// These are the keyword combinations people search when looking for travel agents/trips

export const DESTINATIONS = [
  { name: "Caribbean", slug: "caribbean" },
  { name: "Mediterranean", slug: "mediterranean" },
  { name: "Alaska", slug: "alaska" },
  { name: "Hawaii", slug: "hawaii" },
  { name: "Europe River Cruises", slug: "europe-river-cruises" },
  { name: "Bahamas", slug: "bahamas" },
  { name: "Mexico", slug: "mexico" },
  { name: "Cancun", slug: "cancun" },
  { name: "Jamaica", slug: "jamaica" },
  { name: "Aruba", slug: "aruba" },
  { name: "St. Lucia", slug: "st-lucia" },
  { name: "Turks and Caicos", slug: "turks-and-caicos" },
  { name: "Greece", slug: "greece" },
  { name: "Italy", slug: "italy" },
  { name: "France", slug: "france" },
  { name: "Spain", slug: "spain" },
  { name: "Costa Rica", slug: "costa-rica" },
  { name: "Bali", slug: "bali" },
  { name: "Maldives", slug: "maldives" },
  { name: "Bermuda", slug: "bermuda" },
  { name: "Panama Canal", slug: "panama-canal" },
  { name: "Northern Europe", slug: "northern-europe" },
  { name: "Danube River", slug: "danube-river" },
  { name: "Rhine River", slug: "rhine-river" },
  // Expanded destinations for more search coverage
  { name: "Punta Cana", slug: "punta-cana" },
  { name: "Cabo San Lucas", slug: "cabo-san-lucas" },
  { name: "Riviera Maya", slug: "riviera-maya" },
  { name: "Puerto Rico", slug: "puerto-rico" },
  { name: "US Virgin Islands", slug: "us-virgin-islands" },
  { name: "Barbados", slug: "barbados" },
  { name: "Antigua", slug: "antigua" },
  { name: "Curacao", slug: "curacao" },
  { name: "Grand Cayman", slug: "grand-cayman" },
  { name: "Tahiti", slug: "tahiti" },
  { name: "Bora Bora", slug: "bora-bora" },
  { name: "Fiji", slug: "fiji" },
  { name: "Santorini", slug: "santorini" },
  { name: "Amalfi Coast", slug: "amalfi-coast" },
  { name: "Croatia", slug: "croatia" },
  { name: "Portugal", slug: "portugal" },
  { name: "Iceland", slug: "iceland" },
  { name: "Norway", slug: "norway" },
  { name: "Ireland", slug: "ireland" },
  { name: "England", slug: "england" },
  { name: "Thailand", slug: "thailand" },
  { name: "Japan", slug: "japan" },
  { name: "Australia", slug: "australia" },
  { name: "New Zealand", slug: "new-zealand" },
  { name: "South Africa", slug: "south-africa" },
  { name: "Egypt", slug: "egypt" },
  { name: "Galapagos", slug: "galapagos" },
  { name: "Maui", slug: "maui" },
  { name: "Kauai", slug: "kauai" },
  { name: "Oahu", slug: "oahu" },
  { name: "Dubai", slug: "dubai" },
  { name: "Seychelles", slug: "seychelles" },
  { name: "Zanzibar", slug: "zanzibar" },
] as const

export const TRIP_TYPES = [
  { name: "Cruise", slug: "cruise" },
  { name: "All-Inclusive Resort", slug: "all-inclusive-resort" },
  { name: "Honeymoon", slug: "honeymoon" },
  { name: "Destination Wedding", slug: "destination-wedding" },
  { name: "Family Vacation", slug: "family-vacation" },
  { name: "Luxury Travel", slug: "luxury-travel" },
  { name: "Adventure Travel", slug: "adventure-travel" },
  { name: "Beach Vacation", slug: "beach-vacation" },
  { name: "River Cruise", slug: "river-cruise" },
  { name: "Group Travel", slug: "group-travel" },
  { name: "Romantic Getaway", slug: "romantic-getaway" },
  { name: "Holiday Cruise", slug: "holiday-cruise" },
] as const

export const CRUISE_LINES = [
  { name: "Royal Caribbean", slug: "royal-caribbean" },
  { name: "Norwegian Cruise Line", slug: "norwegian-cruise-line" },
  { name: "Carnival Cruise Line", slug: "carnival-cruise-line" },
  { name: "Celebrity Cruises", slug: "celebrity-cruises" },
  { name: "Disney Cruise Line", slug: "disney-cruise-line" },
  { name: "Viking", slug: "viking" },
  { name: "Seabourn", slug: "seabourn" },
  { name: "AmaWaterways", slug: "amawaterways" },
  { name: "Uniworld", slug: "uniworld" },
  { name: "MSC Cruises", slug: "msc-cruises" },
  { name: "Princess Cruises", slug: "princess-cruises" },
  { name: "Holland America Line", slug: "holland-america-line" },
  { name: "Sandals Resorts", slug: "sandals-resorts" },
  { name: "Beaches Resorts", slug: "beaches-resorts" },
] as const

export const SERVICE_AREAS = [
  { name: "Winter Garden", state: "FL", slug: "winter-garden-fl", zip: "34787", lat: 28.5653, lng: -81.5862, nearby: ["Ocoee", "Windermere", "Orlando", "Clermont"] },
  { name: "Orlando", state: "FL", slug: "orlando-fl", zip: "32801", lat: 28.5383, lng: -81.3792, nearby: ["Winter Garden", "Kissimmee", "Windermere", "Ocoee"] },
  { name: "Windermere", state: "FL", slug: "windermere-fl", zip: "34786", lat: 28.4956, lng: -81.5348, nearby: ["Winter Garden", "Orlando", "Dr. Phillips", "Gotha"] },
  { name: "Ocoee", state: "FL", slug: "ocoee-fl", zip: "34761", lat: 28.5692, lng: -81.5437, nearby: ["Winter Garden", "Orlando", "Apopka", "Pine Hills"] },
  { name: "Clermont", state: "FL", slug: "clermont-fl", zip: "34711", lat: 28.5494, lng: -81.7729, nearby: ["Winter Garden", "Minneola", "Groveland", "Leesburg"] },
  { name: "Kissimmee", state: "FL", slug: "kissimmee-fl", zip: "34741", lat: 28.2920, lng: -81.4076, nearby: ["Orlando", "St. Cloud", "Celebration", "Davenport"] },
  { name: "Lake Nona", state: "FL", slug: "lake-nona-fl", zip: "32827", lat: 28.3697, lng: -81.2418, nearby: ["Orlando", "Kissimmee", "St. Cloud"] },
  { name: "Dr. Phillips", state: "FL", slug: "dr-phillips-fl", zip: "32819", lat: 28.4489, lng: -81.4923, nearby: ["Orlando", "Windermere", "Bay Hill"] },
  { name: "Celebration", state: "FL", slug: "celebration-fl", zip: "34747", lat: 28.3253, lng: -81.5339, nearby: ["Kissimmee", "Orlando", "Davenport"] },
  { name: "Apopka", state: "FL", slug: "apopka-fl", zip: "32703", lat: 28.6934, lng: -81.5322, nearby: ["Ocoee", "Winter Garden", "Altamonte Springs"] },
  { name: "Winter Park", state: "FL", slug: "winter-park-fl", zip: "32789", lat: 28.5999, lng: -81.3392, nearby: ["Orlando", "Maitland", "Casselberry"] },
  { name: "Davenport", state: "FL", slug: "davenport-fl", zip: "33837", lat: 28.1614, lng: -81.6017, nearby: ["Kissimmee", "Clermont", "Haines City"] },
  { name: "Central Florida", state: "FL", slug: "central-florida", zip: null, lat: 28.5383, lng: -81.3792, nearby: ["Orlando", "Winter Garden", "Kissimmee", "Clermont", "Windermere"] },
] as const

// Agent info used across all pSEO pages
export const AGENT_INFO = {
  name: "Richard Johnson",
  business: "Dream Vacations — Richard Johnson & Travel Advisors Group",
  shortBusiness: "Dream Vacations",
  location: "Winter Garden, FL",
  serviceArea: "Central Florida",
  phone: "(407) 951-2398",
  phoneTel: "+14079512398",
  corporateUrl: "https://rpjohnson.dreamvacations.com",
  tagline: "Your Trusted Travel Advisor in Winter Garden, Florida",
  bio: "As your dedicated, full-service travel advisor based in Winter Garden, FL, Richard Johnson is committed to crafting unforgettable vacation experiences. With a passion for travel and specialized expertise in cruises, all-inclusive resorts, tours, and luxury getaways, Richard makes your travel dreams a reality.",
  expertise: [
    "Cruises & Ocean Voyages",
    "All-Inclusive Resort Packages",
    "Destination Weddings & Honeymoons",
    "European River Cruises",
    "Family Vacation Planning",
    "Luxury Travel Experiences",
    "Group Travel Coordination",
    "Tours & Guided Experiences",
  ],
  specialties: [
    "Royal Caribbean",
    "Carnival Cruise Lines",
    "AMA Waterways",
    "Sandals Resorts",
    "Viking Cruises",
    "Seabourn",
    "Uniworld",
  ],
  certifications: [
    "CLIA Certified Travel Advisor",
    "Dream Vacations Franchise Owner",
  ],
  sellerOfTravel: "FL ST-35829",
}

// Local search terms people use — these become city+service combo pages
export const LOCAL_SERVICES = [
  { name: "Travel Agent", slug: "travel-agent" },
  { name: "Cruise Travel Agent", slug: "cruise-travel-agent" },
  { name: "Vacation Planner", slug: "vacation-planner" },
  { name: "Honeymoon Planner", slug: "honeymoon-planner" },
  { name: "Destination Wedding Planner", slug: "destination-wedding-planner" },
  { name: "All-Inclusive Resort Agent", slug: "all-inclusive-resort-agent" },
  { name: "Travel Advisor", slug: "travel-advisor" },
  { name: "River Cruise Specialist", slug: "river-cruise-specialist" },
  { name: "Family Vacation Planner", slug: "family-vacation-planner" },
  { name: "Luxury Travel Agent", slug: "luxury-travel-agent" },
] as const
